FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /workspace
COPY . .
RUN --mount=type=cache,target=/root/.m2 mvn -Pdocker -DskipTests clean package

FROM eclipse-temurin:21-jre-alpine
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY --from=build /workspace/tools-web/target/tools-web-*.jar /app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
